name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adoptopenjdk' 
          java-version: '11'

      - name: Compile Java code
        run: javac -d build/classes $(find . -name "*.java")

      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=你的_SonarCloud_项目Key \
            -Dsonar.organization=你的_SonarCloud_组织ID \
            -Dsonar.sources=. \
            -Dsonar.java.binaries=build/classes \
            -Dsonar.host.url=https://sonarcloud.io
